# Book settings
title: Modeling and Simulation in Python
author: sinotec2

latex:
  latex_documents:
    targetname: book.tex

execute:
  execute_notebooks: 'off'

repository:
  url: https://github.com/sinotec2/jb_test
html:
  use_repository_button: true

parse:
  myst_extended_syntax: true
